# Generated by Django 4.1.7 on 2023-04-02 22:17

from django.db import migrations
from django_rfx.models import PacketType, Protocol
from django_rfx.definitions import PacketTypes


def create_defaults(app, editor):
    for key, value in PacketTypes.items():
        PacketType(id=key, description=value).save()


class Migration(migrations.Migration):
    dependencies = [
        ("django_rfx", "0001_initial"),
    ]

    operations = [migrations.RunPython(create_defaults)]
