# Generated by Django 4.2.1 on 2023-06-15 19:54

from django.db import migrations
from django_rfx.models import Protocol
from django_rfx.definitions import Protocols


def create_defaults(app, editor):
    for key, value in Protocols.items():
        Protocol(description=key, enabled=value).save()


class Migration(migrations.Migration):
    dependencies = [
        ("django_rfx", "0002_defaults"),
    ]

    operations = [migrations.RunPython(create_defaults)]
